namespace SteamLoader.App.Models;

public sealed record StoreSyncDetectedTitleState(
    string Id,
    string StoreId,
    string StoreTitle,
    string StoreItemId,
    string Title,
    string ExecutablePath,
    string StartDirectory,
    string LaunchOptions,
    string EffectiveTitle,
    string EffectiveArtworkTitle,
    uint TargetAppId,
    string SyncAction,
    string SyncDetail,
    string ArtworkState,
    bool Excluded,
    bool HasExistingShortcut,
    bool IsManagedShortcut,
    bool HasOverrides,
    bool HasArtworkMatchCache,
    bool ArtworkLocked,
    string TitleOverride,
    string ArtworkTitleOverride,
    IReadOnlyList<string> DebugLines);
